<svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
  <rect x="14" y="9" width="1" height="1" fill="currentColor"/>
  <rect x="15" y="9" width="1" height="1" fill="currentColor"/>
  <rect x="16" y="9" width="1" height="1" fill="currentColor"/>
  <rect x="12" y="10" width="1" height="1" fill="currentColor"/>
  <rect x="13" y="10" width="1" height="1" fill="currentColor"/>
  <rect x="17" y="10" width="1" height="1" fill="currentColor"/>
  <rect x="18" y="10" width="1" height="1" fill="currentColor"/>
  <rect x="11" y="11" width="1" height="1" fill="currentColor"/>
  <rect x="19" y="11" width="1" height="1" fill="currentColor"/>
  <rect x="10" y="12" width="1" height="1" fill="currentColor"/>
  <rect x="11" y="12" width="1" height="1" fill="currentColor"/>
  <rect x="19" y="12" width="1" height="1" fill="currentColor"/>
  <rect x="20" y="12" width="1" height="1" fill="currentColor"/>
  <rect x="10" y="13" width="1" height="1" fill="currentColor"/>
  <rect x="12" y="13" width="1" height="1" fill="currentColor"/>
  <rect x="13" y="13" width="1" height="1" fill="currentColor"/>
  <rect x="17" y="13" width="1" height="1" fill="currentColor"/>
  <rect x="18" y="13" width="1" height="1" fill="currentColor"/>
  <rect x="20" y="13" width="1" height="1" fill="currentColor"/>
  <rect x="10" y="14" width="1" height="1" fill="currentColor"/>
  <rect x="14" y="14" width="1" height="1" fill="currentColor"/>
  <rect x="15" y="14" width="1" height="1" fill="currentColor"/>
  <rect x="16" y="14" width="1" height="1" fill="currentColor"/>
  <rect x="20" y="14" width="1" height="1" fill="currentColor"/>
  <rect x="10" y="15" width="1" height="1" fill="currentColor"/>
  <rect x="15" y="15" width="1" height="1" fill="currentColor"/>
  <rect x="20" y="15" width="1" height="1" fill="currentColor"/>
  <rect x="10" y="16" width="1" height="1" fill="currentColor"/>
  <rect x="15" y="16" width="1" height="1" fill="currentColor"/>
  <rect x="20" y="16" width="1" height="1" fill="currentColor"/>
  <rect x="10" y="17" width="1" height="1" fill="currentColor"/>
  <rect x="15" y="17" width="1" height="1" fill="currentColor"/>
  <rect x="20" y="17" width="1" height="1" fill="currentColor"/>
  <rect x="11" y="18" width="1" height="1" fill="currentColor"/>
  <rect x="15" y="18" width="1" height="1" fill="currentColor"/>
  <rect x="19" y="18" width="1" height="1" fill="currentColor"/>
  <rect x="12" y="19" width="1" height="1" fill="currentColor"/>
  <rect x="13" y="19" width="1" height="1" fill="currentColor"/>
  <rect x="15" y="19" width="1" height="1" fill="currentColor"/>
  <rect x="17" y="19" width="1" height="1" fill="currentColor"/>
  <rect x="18" y="19" width="1" height="1" fill="currentColor"/>
  <rect x="14" y="20" width="1" height="1" fill="currentColor"/>
  <rect x="15" y="20" width="1" height="1" fill="currentColor"/>
  <rect x="16" y="20" width="1" height="1" fill="currentColor"/>
</svg>
